---
AddModelVirtualAttributeCheck:
AlwaysAddDbIndexCheck: {}
# CheckSaveReturnValueCheck: {}
# CheckDestroyReturnValueCheck: {}
DefaultScopeIsEvilCheck: {}
DryBundlerInCapistranoCheck: {}
# HashSyntaxCheck: {}
IsolateSeedDataCheck: {}
KeepFindersOnTheirOwnModelCheck: {}
LawOfDemeterCheck: {}
# LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: {}
MoveCodeIntoHelperCheck: { array_count: 10 }
MoveCodeIntoModelCheck: { use_count: 10 }
MoveFinderToNamedScopeCheck: {}
MoveModelLogicIntoModelCheck: { use_count: 10 }
NeedlessDeepNestingCheck: { nested_count: 5 }
NotRescueExceptionCheck: {}
NotUseDefaultRouteCheck: {}
NotUseTimeAgoInWordsCheck: {}
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: {}
RemoveEmptyHelpersCheck: {}
# RemoveTabCheck: {}
RemoveTrailingWhitespaceCheck: {}
# RemoveUnusedMethodsInControllersCheck: { except_methods: [] }
# RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
# RemoveUnusedMethodsInModelsCheck: { except_methods: [] }
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 5 }
ReplaceInstanceVariableWithLocalVariableCheck: {}
RestrictAutoGeneratedRoutesCheck: {}
SimplifyRenderInControllersCheck: {}
SimplifyRenderInViewsCheck: {}
# UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: {}
UseMultipartAlternativeAsContentTypeOfEmailCheck: {}
# UseParenthesesInMethodDefCheck: {}
UseObserverCheck: {}
UseQueryAttributeCheck: {}
UseSayWithTimeInMigrationsCheck: {}
UseScopeAccessCheck: {}
UseTurboSprocketsRails3Check: {}
